Backend/ShoppeeWebsite/Food_Web/Areas/Store/Controllers/AccController.cs
using Microsoft.AspNet.Identity.Owin;
using System;
using System.Net;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using Food_Web.Models;
using Microsoft.AspNet.Identity;
using static Food_Web.Models.ManageController;

namespace Food_Web.Areas.Store.Controllers
{
    public class AccController : Controller
    {
        // GET: Store/Acc
        public ActionResult Index()
        {
            var userId = User.Identity.GetUserId();

            if (userId == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var userManager = HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            var user = userManager.FindById(userId);

            if (user == null)
            {
                return HttpNotFound();
            }

            return View(user);
        }
        public ActionResult Logoff()
        {
            // Perform logout logic

            return RedirectToAction("Index", "Product");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Save(ApplicationUser user)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    var userManager = HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
                    var currentUser = await userManager.FindByNameAsync(User.Identity.Name);

                    if (currentUser != null)
                    {
                        currentUser.Email = user.Email;
                        currentUser.PhoneNumber = user.PhoneNumber;
                        currentUser.Fullname = user.Fullname;
                        currentUser.Adress = user.Adress;
                        currentUser.Opentime = user.Opentime;
                        currentUser.Closetime = user.Closetime;
                        // Gán các thuộc tính khác của người dùng từ form

                        var result = await userManager.UpdateAsync(currentUser);

                        if (result.Succeeded)
                        {
                            return RedirectToAction("Index");
                        }
                        else
                        {
                            // Xử lý khi cập nhật thất bại
                            // Có thể thêm các thông báo lỗi vào ModelState
                            foreach (var error in result.Errors)
                            {
                                ModelState.AddModelError("", error);
                            }
                        }
                    }
                    else
                    {
                        return HttpNotFound();
                    }
                }
                catch (Exception)
                {
                    // Xử lý khi có lỗi xảy ra trong quá trình lưu dữ liệu
                    ModelState.AddModelError("", "An error occurred while saving the user.");
                }
            }

            return View("Index", user);
        }
        // Get View using this Method

    }
}

Backend/ShoppeeWebsite/Food_Web/Areas/Store/Views/Acc/ChangePassword.cshtml
@using Microsoft.AspNet.Identity
@using Microsoft.AspNet.Identity.EntityFramework
@using Food_Web.Models

@model ApplicationUser
@{
    ViewBag.Title = "ChangePassword";
    Layout = "~/Views/Shared/_LayoutStore.cshtml";
}

@using (Html.BeginForm("ChangePassword", "Acc", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
{
    @Html.AntiForgeryToken()

    <div class="form-group">
        @Html.LabelFor(model => model.OldPassword, new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.PasswordFor(model => model.OldPassword, new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.OldPassword)
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.NewPassword, new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.PasswordFor(model => model.NewPassword, new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.NewPassword)
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.ConfirmPassword, new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.PasswordFor(model => model.ConfirmPassword, new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.ConfirmPassword)
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Change Password" class="btn btn-default" />
        </div>
    </div>
}

Backend/ShoppeeWebsite/Food_Web/Areas/Store/Views/Acc/Index.cshtml
@using Microsoft.AspNet.Identity
@using Microsoft.AspNet.Identity.EntityFramework
@using Food_Web.Models

@model ApplicationUser

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutStore.cshtml";
}

@using (Html.BeginForm("Save", "Acc", FormMethod.Post))
{
    @Html.AntiForgeryToken()

    <div class="card shadow mb-4">
        <div class="card-header py-3" style="display:flex; align-items:center; justify-content:space-between">
            <h6 class="m-0 font-weight-bold text-primary" style="user-select:none"><a href="~/Store/Productss/Index">← Quay lại</a></h6>
            <input type="submit" value="Save" class="btn btn-primary" />

        </div>
        <div class="card-body">
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <!-- Search -->
            <div class="row">
                @*<div class="col-md-4 box-upload">
                        <label>
                            <img src="~/Content/products/@Model.Image" style="height: 320px; padding: 5px 0; border-radius: 15px;" id="preview" />
                            <div class="col-md-10" style=" display: none;">
                                <input type="file" name="Picture" required calss="form-control" id="images" accept=".png, .jpg, .jpeg" required onchange="showImage(this, document.getElementById('preview'))" />
                            </div>
                        </label>
                    </div>*@

                <div class="col-md-8">
                    <div class="form-group" style="display: flex; justify-content:center">
                        <div class="col-sm-4">
                            <label>Tên Sản Phẩm: </label>
                            @Html.TextBoxFor(m => m.Email, new { @class = "form-control form-control-sm", style = "width: 250px; padding: 7px 5px;" })
                            @Html.ValidationMessageFor(m => m.Email, "", new { @class = "text-danger", style = "display: block; margin: 5px auto;" })
                        </div>
                        <div class="col-sm-4">
                            <label>Tên Sản Phẩm: </label>
                            @Html.TextBoxFor(m => m.UserName, new { @class = "form-control form-control-sm", style = "width: 250px; padding: 7px 5px;" })
                            @Html.ValidationMessageFor(m => m.UserName, "", new { @class = "text-danger", style = "display: block; margin: 5px auto;" })
                        </div>
                    </div>
                    <div class="form-group" style="display: flex; justify-content:center">
                        <div class="col-sm-4">
                            <label>Giá Nhập: </label>
                            @Html.TextBoxFor(m => m.Fullname, new { @class = "form-control form-control-sm", style = "width: 250px; padding: 7px 5px;" })
                            @Html.ValidationMessageFor(m => m.Fullname, "", new { @class = "text-danger", style = "display: block; margin: 5px auto;" })
                        </div>
                        <div class="col-sm-4">
                            <label>Giá Nhập: </label>
                            @Html.TextBoxFor(m => m.PhoneNumber, new { @class = "form-control form-control-sm", style = "width: 250px; padding: 7px 5px;" })
                            @Html.ValidationMessageFor(m => m.PhoneNumber, "", new { @class = "text-danger", style = "display: block; margin: 5px auto;" })
                        </div>
                    </div>

                    <div class="form-group" style="display: flex; justify-content:center">

                        <div class="col-sm-4">
                            <label>Mo ta Dai: </label>
                            @Html.TextBoxFor(m => m.Opentime, new { @class = "form-control form-control-sm", style = "width: 250px; padding: 7px 5px;" })
                            @Html.ValidationMessageFor(m => m.Opentime, "", new { @class = "text-danger", style = "display: block; margin: 5px auto;" })
                        </div>
                        <div class="col-sm-4">
                            <label>Mo ta ngan: </label>
                            @Html.TextBoxFor(m => m.Closetime, new { @class = "form-control form-control-sm", style = "width: 250px; padding: 7px 5px;" })
                            @Html.ValidationMessageFor(m => m.Closetime, "", new { @class = "text-danger", style = "display: block; margin: 5px auto;" })
                        </div>
                    </div>
                    <div class="form-group" style="display: flex; justify-content:center">
                        <div class="col-sm-4">
                            <label>Mo ta ngan: </label>
                            @Html.TextBoxFor(m => m.Adress, new { @class = "form-control form-control-sm", style = "width: 250px; padding: 7px 5px;" })
                            @Html.ValidationMessageFor(m => m.Adress, "", new { @class = "text-danger", style = "display: block; margin: 5px auto;" })
                        </div>

                    </div>
                </div>

            </div>
        </div>
    </div>
}

@Scripts.Render("~/bundles/jqueryval")
<script type="text/javascript">
    function showImage(upload, preview) {
        if (upload.files && upload.files[0]) {
            var reader = new FileReader();
            reader.onload = function (e) {
                $(preview).attr('src', e.target.result);
            }
            reader.readAsDataURL(upload.files[0]);
        }
    }
</script>
}
<style>
    img#preview {
        margin: 0px 24px 17px 174px
    }

    label.btnChoose {
        margin: -60px 255px;
    }

    .btnChoose input {
        display: none;
    }
</style>