Backend/ShoppeeWebsite/Food_Web/Models/SetHotViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.NetworkInformation;
using System.Web;
using System.Web.Mvc;


namespace Food_Web.Models
{
    public class SetHotViewModel
    {
        public List<SelectListItem> Products { get; set; }
        public int SelectedProductId { get; set; }
    }
}

Backend/ShoppeeWebsite/Food_Web/Areas/Store/Controllers/ProductssController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Food_Web.Models;
using Microsoft.AspNet.Identity;
using System.IO;
using System.Data.Entity.Infrastructure; // For Entity Framework 6
using Excel = Microsoft.Office.Interop.Excel;
using Microsoft.Office.Interop.Word;
using OfficeOpenXml;
using OfficeOpenXml.Style;
using System.Web.UI.WebControls;
using DocumentFormat.OpenXml.Packaging;
using DocumentFormat.OpenXml.Wordprocessing;
using DocumentFormat.OpenXml;
using DocumentFormat.OpenXml.Spreadsheet;
using DevExpress.Skins;
using PagedList;
namespace Food_Web.Areas.Store.Controllers
{
    public class ProductssController : Controller
    {
        private FoodcontextDB db = new FoodcontextDB();


        public ActionResult Index(int? page, string searchString)
        {
            // Lấy thông tin người dùng đăng nhập
            var userId = User.Identity.GetUserId();

            var pageSize = 5; // Số sản phẩm hiển thị trên mỗi trang
            var pageNumber = (page ?? 1); // Trang hiện tại

            // Lấy danh sách sản phẩm thuộc người dùng đăng nhập và thực hiện tìm kiếm nếu có
            var products = db.Products
                .Where(p => p.Userid == userId && (string.IsNullOrEmpty(searchString) || p.Productname.Contains(searchString)))
                .Include(p => p.Category)
                .OrderBy(p => p.Productid) // Sắp xếp theo một trường nào đó (ví dụ: ProductId)
                .ToPagedList(pageNumber, pageSize);
            ViewBag.SearchString = searchString; // Truyền searchString để giữ giá trị nhập vào ô tìm kiếm
            return View(products);
        }
        // GET: Store/Productss/Details/5
        [HttpGet]
        public ActionResult Indextl(int? categoryId)
        {
            var userId = User.Identity.GetUserId();

            var products = db.Products
                .Where(p => p.Userid == userId && (categoryId == null || p.Categoryid == categoryId))
                .Include(p => p.Category)
                .ToList();

            var categories = db.Categories.ToList();
            ViewBag.CategoryId = new SelectList(categories, "Categoryid", "Categoryname", categoryId);

            if (Request.IsAjaxRequest())
            {
                return PartialView("_ProductListPartial", products);
            }
            Session["SelectedCategoryId"] = categoryId;
            return View(products);
        }
        public ActionResult Exporttl()
        {
            var userId = User.Identity.GetUserId();
            var selectedCategoryId = Session["SelectedCategoryId"] as int?;

            List<Product> products;

            if (selectedCategoryId.HasValue)
            {
                products = db.Products
                    .Where(p => p.Userid == userId && p.Categoryid == selectedCategoryId)
                    .ToList();
            }
            else
            {
                products = db.Products
                    .Where(p => p.Userid == userId)
                    .ToList();
            }

            using (var package = new ExcelPackage())
            {
                var worksheet = package.Workbook.Worksheets.Add("Products");

                // Set the header row
                worksheet.Cells[1, 1].Value = "Product ID";
                worksheet.Cells[1, 2].Value = "Product Name";
                worksheet.Cells[1, 3].Value = "Price";
                worksheet.Cells[1, 4].Value = "Description";
                worksheet.Cells[1, 5].Value = "Category";
                worksheet.Cells[1, 6].Value = "Sort Description";
                worksheet.Cells[1, 7].Value = "Status";

                // Populate data rows
                for (int i = 0; i < products.Count; i++)
                {
                    var product = products[i];
                    worksheet.Cells[i + 2, 1].Value = product.Productid;
                    worksheet.Cells[i + 2, 2].Value = product.Productname;
                    worksheet.Cells[i + 2, 3].Value = product.price;
                    worksheet.Cells[i + 2, 4].Value = product.discription;
                    worksheet.Cells[i + 2, 5].Value = product.Category?.Categoryname;
                    worksheet.Cells[i + 2, 6].Value = product.sortdiscription;
                    worksheet.Cells[i + 2, 7].Value = product.status ? "Active" : "Inactive";
                }

                // Auto-fit columns
                worksheet.Cells.AutoFitColumns();

                Response.Clear();
                Response.ContentType = "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet";
                Response.AddHeader("content-disposition", "attachment; filename=Products.xlsx");
                Response.BinaryWrite(package.GetAsByteArray());
                Response.End();
            }

            return View("success");
        }

        [HttpPost]
        public ActionResult Import(HttpPostedFileBase file)
        {
            if (file != null && file.ContentLength > 0)
            {
                try
                {
                    using (var package = new ExcelPackage(file.InputStream))
                    {
                        var worksheet = package.Workbook.Worksheets.First();

                        int rowCount = worksheet.Dimension.Rows;

                        // Assuming the header row is present
                        for (int row = 2; row <= rowCount; row++)
                        {
                            var newProduct = new Product
                            {
                                Userid = User.Identity.GetUserId(),
                                DateCreated = DateTime.Now,
                                Productname = worksheet.Cells[row, 2].Value?.ToString(),
                                price = Convert.ToInt32(worksheet.Cells[row, 3].Value),
                                discription = worksheet.Cells[row, 4].Value?.ToString(),
                                sortdiscription = worksheet.Cells[row, 6].Value?.ToString(),
                                status = worksheet.Cells[row, 7].Value?.ToString().Equals("Active", StringComparison.OrdinalIgnoreCase) ?? false,
                                Soluong = Convert.ToInt32(worksheet.Cells[row, 8].Value),
                                image = worksheet.Cells[row, 9].Value?.ToString()
                            };

                            // Get the category name from the Excel file
                            var categoryName = worksheet.Cells[row, 5].Value?.ToString();
                            if (!string.IsNullOrEmpty(categoryName))
                            {
                                var category = db.Categories.FirstOrDefault(c => c.Categoryname == categoryName);
                                if (category != null)
                                {
                                    newProduct.Categoryid = category.Categoryid;
                                }
                            }
                            var imageFile = worksheet.Cells[row, 9].Value?.ToString();

                            if (!string.IsNullOrEmpty(imageFile))
                            {
                                // Handle data URI prefix if present
                                var dataUriPrefix = "data:image/png;base64,";
                                if (imageFile.StartsWith(dataUriPrefix))
                                {
                                    imageFile = imageFile.Substring(dataUriPrefix.Length);
                                }

                                // Trim whitespaces
                                imageFile = imageFile.Trim();

                                try
                                {
                                    // Generate unique image name based on Productid
                                    var fileType = GetFileExtension(imageFile);
                                    var imageName = newProduct.Productid + "_img" + fileType;
                                    var filePath = Path.Combine(Server.MapPath("~/Content/products"), imageName);

                                    // Save the image file
                                    byte[] imageData = Convert.FromBase64String(imageFile);
                                    System.IO.File.WriteAllBytes(filePath, imageData);

                                    // Update the newProduct object with the image path
                                    newProduct.image = imageName;
                                }
                                catch (Exception ex)
                                {
                                    // Log the exception or handle it appropriately
                                    Console.WriteLine($"Error converting Base64 to byte array: {ex.Message}");
                                }
                            }
                            // Add the new product to the database
                            db.Products.Add(newProduct);
                        }

                        // Save changes to the database
                        db.SaveChanges();

                        return Json(new { success = true, message = "Import successful" });
                    }
                }
                catch (Exception ex)
                {
                    ModelState.AddModelError("", "Error during import: " + ex.Message);
                }
            }
            else
            {
                ModelState.AddModelError("", "No file selected");
            }

            return Json(new { success = false, message = "Invalid file or other validation errors" });
        }

        private string GetFileExtension(string fileName)
        {
            if (string.IsNullOrEmpty(fileName))
            {
                return null;
            }

Backend/ShoppeeWebsite/Food_Web/Areas/Store/Views/Productss/ClearDiscount.cshtml
@{
    ViewBag.Title = "ClearDiscount";
    Layout = "~/Views/Shared/_LayoutStore.cshtml";
}

<h2>ClearDiscount</h2>

Backend/ShoppeeWebsite/Food_Web/Areas/Store/Views/Productss/Create.cshtml
@model Food_Web.Models.Product

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_LayoutStore.cshtml";
}

<script src="https://cdn.tiny.cloud/1/YOUR_API_KEY/tinymce/5/tinymce.min.js" referrerpolicy="origin"></script>
<form action="@Url.Action("Import", "Productss")" method="post" enctype="multipart/form-data">
    <label for="file">Import Excel:</label>
    <input type="file" name="file" id="file" accept=".xlsx, .xls" />
    <button type="submit" class="btn btn-success">Import</button>
</form>
@using (Html.BeginForm("Create", "Productss", FormMethod.Post, new { enctype = "multipart/form-data", @class = "container mt-4" }))
{
    @Html.AntiForgeryToken()

    <h1 class="text-center h3 mb-2 text-gray-800">Thêm Sản Phẩm</h1>

    <div class="card shadow mb-4">
        <div class="card-header py-3 d-flex justify-content-between">
            <h6 class="m-0 font-weight-bold text-primary" style="user-select:none">
                <a href="~/Store/Productss/Index" class="text-decoration-none">← Quay lại</a>
            </h6>
            <button type="submit" value="Create" class="btn btn-primary">Thêm</button>
        </div>
        <div class="card-body">
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })

            <div class="row">
                <div class="col-md-4 box-upload">
                    <label for="mainImage" class="form-label">
                        Main Product Image
                        <img src="~/Content/erro.jpg" class="img-fluid mt-3" id="preview" />
                        @Html.ValidationMessageFor(m => m.image, "", new { @class = "text-danger", style = "display: block; margin: 5px;" })
                        <input type="file" name="MainImage" class="form-control mt-3" id="mainImage" accept=".png, .jpg, .jpeg" required onchange="showImage(this, document.getElementById('preview'))" />
                    </label>
                </div>

                <div class="col-md-4 box-upload">
                    <label for="extraImages" class="form-label">
                        Extra Product Images
                        <div id="extraImagesPreview" class="d-flex flex-wrap"></div>
                        <input type="file" name="ExtraImages" class="form-control mt-3" id="extraImages" accept=".png, .jpg, .jpeg" multiple required onchange="showImages(this, document.getElementById('extraImagesPreview'))" />
                    </label>
                </div>

                <div class="col-md-8">
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <label for="Productname">Tên Sản Phẩm</label>
                                @Html.TextBoxFor(m => m.Productname, new { @class = "form-control", style = "width: 100%" })
                                @Html.ValidationMessageFor(m => m.Productname, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="col-md-6">
                            <div class="form-group">
                                <label for="price">Giá Nhập</label>
                                @Html.TextBoxFor(m => m.price, new { @class = "form-control", style = "width: 100%" })
                                @Html.ValidationMessageFor(m => m.price, "", new { @class = "text-danger" })
                            </div>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <label for="Categoryid">Thể Loại</label>
                                @Html.DropDownList("Categoryid", null, htmlAttributes: new { @class = "form-control", style = "width: 100%" })
                                @Html.ValidationMessageFor(model => model.Categoryid, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="col-md-6">
                            <div class="form-group">
                                <label for="sortdiscription">Mô tả ngắn</label>
                                @Html.TextBoxFor(m => m.sortdiscription, new { @class = "form-control", style = "width: 100%" })
                                @Html.ValidationMessageFor(m => m.sortdiscription, "", new { @class = "text-danger" })
                            </div>
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="Soluong">Số Lượng</label>
                        @Html.TextBoxFor(m => m.Soluong, new { @class = "form-control", style = "width: 100%", type = "number", min = "1" })
                        @Html.ValidationMessageFor(m => m.Soluong, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="col-md-12">
                    <div class="form-group">
                        <label for="discription-editor">Mô tả</label>
                        <textarea id="discription-editor" name="discription" class="form-control"></textarea>
                        @Html.ValidationMessageFor(model => model.discription, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script type="text/javascript">
        function showImages(upload, extraPreview) {
            extraPreview.innerHTML = "";
            var selectedImages = [];

            if (upload.files && upload.files.length > 0) {
                for (var i = 0; i < upload.files.length; i++) {
                    var reader = new FileReader();
                    reader.onload = function (e) {
                        var img = document.createElement("img");
                        img.src = e.target.result;
                        img.style.height = "100px";
                        img.style.margin = "5px";
                        img.style.cursor = "pointer";
                        img.onclick = function () {
                            if (selectedImages.includes(this.src)) {
                                selectedImages = selectedImages.filter(item => item !== this.src);
                            } else {
                                selectedImages.push(this.src);
                            }
                            document.getElementById("selectedExtraImages").value = JSON.stringify(selectedImages);
                        };
                        extraPreview.appendChild(img);
                    };
                    reader.readAsDataURL(upload.files[i]);
                }
            }
        }


        tinymce.init({
            selector: '#discription-editor',
            height: 250,
            plugins: 'advlist autolink lists link image imagetools charmap print preview',
            toolbar: 'undo redo | bold italic underline | formatselect | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image',
        });
    </script>
}
<style>
    element.style {
        margin-left: 816px;
        margin-top: -231px;
        width: 1101px;
    }
</style>

Backend/ShoppeeWebsite/Food_Web/Areas/Store/Views/Productss/CreateDiscount.cshtml
@model List<Food_Web.Models.Product>

@{
    ViewBag.Title = "Create Discount";
    Layout = "~/Views/Shared/_LayoutStore.cshtml";
}
<div class="card shadow mb-4">
    <div class="card-header py-3">
        <h6 class="m-0 font-weight-bold text-primary">@Html.ActionLink("Trang Chủ", "Index", "Homes") / @Html.ActionLink("Sản Phẩm", "Index", "Productss")</h6>
    </div>
    @using (Html.BeginForm("CreateDiscount", "Productss"))
    {
        <div class="form-group">
            <label for="product">Sản phẩm:</label>
            @Html.DropDownList("Productid", ViewBag.Products as SelectList, new { @class = "form-control" })
        </div>
        <div class="form-group">
            <label for="discountPercent">Phần trăm giảm giá:</label>
            @Html.TextBox("discountPercent", null, new { @class = "form-control", type = "number", min = 0, max = 100 })
        </div>
        <button type="submit" class="btn btn-primary">Lưu</button>
    }
</div>

Backend/ShoppeeWebsite/Food_Web/Areas/Store/Views/Productss/Edit.cshtml
@model Food_Web.Models.Product

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_LayoutStore.cshtml";
}

@using (Html.BeginForm("Edit", "Productss", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="card shadow mb-4">
        <input type="hidden" name="Productid" value="@Model.Productid" />
        <div class="card-header py-3" style="display:flex; align-items:center; justify-content:space-between">
            <h6 class="m-0 font-weight-bold text-primary" style="user-select:none"><a href="~/Store/Productss/Index">← Quay lại</a></h6>
            <button type="submit" value="Edit" class="btn btn-primary">Thêm</button>

        </div>
        <div class="card-body">
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <!-- Search -->
            <div class="row">
                <div class="col-md-4 box-upload">
                    <label>
                        <img src="~/Content/products/@Model.image" style="height: 320px; padding: 5px 0; border-radius: 15px;" id="preview" />
                        <div class="col-md-10" style=" display: none;">
                            <input type="file" name="Picture" required calss="form-control" id="images" accept=".png, .jpg, .jpeg" required onchange="showImage(this, document.getElementById('preview'))" />
                        </div>
                    </label>
                </div>
                <div class="form-group">
                    @foreach (var extraImage in Model.extrafoods)
                    {
                        <img src="~/Content/products/@extraImage.image" alt="Product Image" style="max-width: 100px; max-height: 100px" />
                        <a href="@Url.Action("DeleteImage", "Productss", new { id = extraImage.Productid, imageId = extraImage.ext_id })">Delete</a>
                        <br />
                    }

                    <div class="col-md-4 box-upload">
                        <label for="extraImages">
                            Extra Product Images
                            <div id="extraImagesPreview" style="display: flex; flex-wrap: wrap;"></div>
                            <input type="file" name="ExtraImages" class="form-control" id="extraImages" accept=".png, .jpg, .jpeg" multiple onchange="showImages(this, document.getElementById('extraImagesPreview'))" />
                        </label>
                    </div>

                </div>
                <div class="col-md-8">
                    <div class="form-group" style="display: flex; justify-content:center">
                        <div class="col-sm-4">
                            <label>Tên Sản Phẩm: </label>
                            @Html.TextBoxFor(m => m.Productname, new { @class = "form-control form-control-sm", style = "width: 250px; padding: 7px 5px;" })
                            @Html.ValidationMessageFor(m => m.Productname, "", new { @class = "text-danger", style = "display: block; margin: 5px auto;" })
                        </div>
                        <div class="col-sm-4">
                            <label>Ngày Tạo: </label>
                            <input readonly name="DateCreated" value="@DateTime.Now.ToString("dd/MM/yyyy HH:ss")" class="form-control form-control-sm" style="width: 250px; padding: 7px 5px; " />
                        </div>
                    </div>
                    <div class="form-group" style="display: flex; justify-content:center">
                        <div class="col-sm-4">
                            <label>Giá Nhập: </label>
                            @Html.TextBoxFor(m => m.price, new { @class = "form-control form-control-sm", style = "width: 250px; padding: 7px 5px;" })
                            @Html.ValidationMessageFor(m => m.price, "", new { @class = "text-danger", style = "display: block; margin: 5px auto;" })
                        </div>
                        <div class="col-sm-4">
                            <label>Thể Loại: </label>
                            @Html.DropDownList("Categoryid", null, htmlAttributes: new { @class = "form-control form-control-sm;  padding: 10px 5px; ", style = "width: 250px; padding: 7px 5px;" })
                            @Html.ValidationMessageFor(model => model.Categoryid, "", new { @class = "text-danger", style = "display: block; margin: 5px auto;" })
                        </div>
                    </div>
                    <div class="form-group" style="display: flex; justify-content:center">
                        <div class="col-sm-4">
                            <label>Mo ta ngan: </label>
                            @Html.TextBoxFor(m => m.discription, new { @class = "form-control form-control-sm", style = "width: 250px; padding: 7px 5px;" })
                            @Html.ValidationMessageFor(m => m.Productname, "", new { @class = "text-danger", style = "display: block; margin: 5px auto;" })
                        </div>
                        <div class="col-sm-4">
                            <label>Mo ta Dai: </label>
                            @Html.TextBoxFor(m => m.sortdiscription, new { @class = "form-control form-control-sm", style = "width: 250px; padding: 7px 5px;" })
                            @Html.ValidationMessageFor(m => m.sortdiscription, "", new { @class = "text-danger", style = "display: block; margin: 5px auto;" })
                        </div>

                    </div>
                </div>

            </div>
        </div>
    </div>
}

@Scripts.Render("~/bundles/jqueryval")
<script type="text/javascript">
    //function showImage(upload, preview) {
    //    if (upload.files && upload.files[0]) {
    //        var reader = new FileReader();
    //        reader.onload = function (e) {
    //            $(preview).attr('src', e.target.result);
    //        }
    //        reader.readAsDataURL(upload.files[0]);
    //    }
    //}

    function showImages(upload, extraPreview) {
        extraPreview.innerHTML = "";
        var selectedImages = [];

        if (upload.files && upload.files.length > 0) {
            for (var i = 0; i < upload.files.length; i++) {
                var reader = new FileReader();
                reader.onload = function (e) {
                    var img = document.createElement("img");
                    img.src = e.target.result;
                    img.style.height = "100px";
                    img.style.margin = "5px";
                    img.style.cursor = "pointer";
                    img.onclick = function () {
                        if (selectedImages.includes(this.src)) {
                            selectedImages = selectedImages.filter(item => item !== this.src);
                        } else {
                            selectedImages.push(this.src);
                        }
                        document.getElementById("selectedExtraImages").value = JSON.stringify(selectedImages);
                    };
                    extraPreview.appendChild(img);
                };
                reader.readAsDataURL(upload.files[i]);
            }
        }
    }
</script>
}
<style>
    img#preview {
        margin: 0px 24px 17px 174px
    }

    label.btnChoose {
        margin: -60px 255px;
    }

    .btnChoose input {
        display: none;
    }
</style>

Backend/ShoppeeWebsite/Food_Web/Areas/Store/Views/Productss/EditSale.cshtml
@model Food_Web.Models.Product

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_LayoutStore.cshtml";
}

@using (Html.BeginForm("EditSale", "Productss", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="card shadow mb-4">
        <input type="hidden" name="Productid" value="@Model.Productid" />
        <div class="card-header py-3" style="display:flex; align-items:center; justify-content:space-between">
            <h6 class="m-0 font-weight-bold text-primary" style="user-select:none"><a href="~/Store/Productss/Index">← Quay lại</a></h6>
            <button type="submit" value="Edit" class="btn btn-primary">Thêm</button>

        </div>
        <div class="card-body">
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <!-- Search -->
            <div class="row">
                <div class="col-md-4 box-upload">
                    <label>
                        <img src="~/Content/products/@Model.image" style="height: 320px; padding: 5px 0; border-radius: 15px;" id="preview" />

                    </label>
                </div>

                <div class="col-md-8">
                    <div class="form-group" style="display: flex; justify-content:center">
                        <div class="col-sm-4">
                            <label>Tên Sản Phẩm: </label>
                            @Html.TextBoxFor(m => m.Productname, new { @class = "form-control form-control-sm", style = "width: 250px; padding: 7px 5px;" })
                            @Html.ValidationMessageFor(m => m.Productname, "", new { @class = "text-danger", style = "display: block; margin: 5px auto;" })
                        </div>
                        <div class="col-sm-4">
                            <label>Ngày Tạo: </label>
                            <input readonly name="DateCreated" value="@DateTime.Now.ToString("dd/MM/yyyy HH:ss")" class="form-control form-control-sm" style="width: 250px; padding: 7px 5px; " />
                        </div>
                    </div>
                    <div class="form-group" style="display:none">
                        @Html.LabelFor(model => model.Userid, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Userid, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Userid, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="form-group" style="display: flex; justify-content:center">
                        <div class="col-sm-4">
                            <label>Giá Nhập: </label>
                            @Html.TextBoxFor(m => m.price, new { @class = "form-control form-control-sm", style = "width: 250px; padding: 7px 5px;" })
                            @Html.ValidationMessageFor(m => m.price, "", new { @class = "text-danger", style = "display: block; margin: 5px auto;" })
                        </div>
                        <div class="col-sm-4">
                            <label>Thể Loại: </label>
                            @Html.DropDownList("Categoryid", null, htmlAttributes: new { @class = "form-control form-control-sm;  padding: 10px 5px; ", style = "width: 250px; padding: 7px 5px;" })
                            @Html.ValidationMessageFor(model => model.Categoryid, "", new { @class = "text-danger", style = "display: block; margin: 5px auto;" })
                        </div>
                    </div>
                    <div class="form-group" style="display: flex; justify-content:center">
                        <div class="col-sm-4">
                            <label>Mo ta ngan: </label>
                            @Html.TextBoxFor(m => m.discription, new { @class = "form-control form-control-sm", style = "width: 250px; padding: 7px 5px;" })
                            @Html.ValidationMessageFor(m => m.discription, "", new { @class = "text-danger", style = "display: block; margin: 5px auto;" })
                        </div>
                        <div class="col-sm-4">
                            <label>Mo ta Dai: </label>
                            @Html.TextBoxFor(m => m.DiscountPercent, new { @class = "form-control form-control-sm", style = "width: 250px; padding: 7px 5px;" })
                            @Html.ValidationMessageFor(m => m.DiscountPercent, "", new { @class = "text-danger", style = "display: block; margin: 5px auto;" })
                        </div>

                    </div>
                </div>

            </div>
        </div>
    </div>
}

@Scripts.Render("~/bundles/jqueryval")
<script type="text/javascript">
    function showImage(upload, preview) {
        if (upload.files && upload.files[0]) {
            var reader = new FileReader();
            reader.onload = function (e) {
                $(preview).attr('src', e.target.result);
            }
            reader.readAsDataURL(upload.files[0]);
        }
    }
</script>
}
<style>
    img#preview {
        margin: 0px 24px 17px 174px
    }

    label.btnChoose {
        margin: -60px 255px;
    }

    .btnChoose input {
        display: none;
    }
</style>